-- Insertion des données
INSERT INTO starter_card (id, name, description, img_url, family, affinity, hp, energy, attack, defense, prix) VALUES
(1, 'Warrior of Light', 'A brave warrior of the ancient order.', 'cards/warrioroflight.jpg', 'warrior', 'fire', 20, 15, 25, 20, 55),
(2, 'Mystic Mage', 'A mage with unparalleled control over arcane forces.', 'cards/mysticmage.jpg', 'mage', 'arcane', 15, 30, 20, 10, 55),
(3, 'Shadow Rogue', 'A rogue that moves unseen in the shadows.', 'cards/shadowrogue.jpeg', 'rogue', 'darkness', 25, 20, 30, 15, 70),
(4, 'Valiant Knight', 'A knight who defends the realm with honor.', 'cards/valiantknight.jpg', 'knight', 'earth', 30, 15, 25, 30, 75),
(5, 'Holy Cleric', 'A cleric with divine healing powers.', 'cards/holycleric.jpg', 'cleric', 'light', 25, 30, 15, 20, 70),
(6, 'Bard of Valor', 'A bard who inspires courage through song.', 'cards/bardvalor.jpg', 'bard', 'wind', 15, 20, 15, 10, 45),
(7, 'Fiery Warrior', 'A warrior who channels the power of fire.', 'cards/fierywarrior.jpg', 'warrior', 'fire', 35, 25, 30, 20, 85),
(8, 'Arcane Wizard', 'A wizard with mastery over arcane arts.', 'cards/arcanewizard.jpg', 'mage', 'arcane', 10, 40, 20, 15, 70),
(9, 'Silent Assassin', 'A rogue known for silent takedowns.', 'cards/silentassasin.jpg', 'rogue', 'darkness', 30, 25, 35, 20, 85),
(10, 'Guardian Knight', 'A knight dedicated to protecting the weak.', 'cards/guardianknight.jpg', 'knight', 'earth', 40, 20, 25, 35, 105),
(11, 'Divine Priest', 'A cleric with a connection to the divine.', 'cards/divinepriest.jpg', 'cleric', 'light', 30, 35, 20, 25, 85),
(12, 'Songweaver', 'A bard who weaves magic into their music.', 'cards/Songweaver.jpg', 'bard', 'wind', 20, 30, 25, 20, 75),
(13, 'Dragon Slayer', 'A warrior famed for slaying dragons.', 'cards/dragonslayer.jpg', 'warrior', 'fire', 45, 35, 40, 25, 110),
(14, 'Ice Sorcerer', 'A mage with control over ice and snow.', 'cards/icesorcerer.jpg', 'mage', 'ice', 15, 35, 30, 20, 75),
(15, 'Night Stalker', 'A rogue who prowls under the cover of night.', 'cards/Night Stalker.jpg', 'rogue', 'darkness', 25, 20, 35, 25, 80),
(16, 'Steel Paladin', 'A knight in shining armor.', 'cards/SteelPaladin.jpg', 'knight', 'earth', 40, 15, 30, 35, 90),
(17, 'Celestial Healer', 'A cleric with unmatched healing abilities.', 'cards/CelestialHealer.jpg', 'cleric', 'light', 35, 40, 20, 25, 95),
(18, 'Windrunner', 'A bard swift as the wind.', 'cards/Windrunner.jpg', 'bard', 'wind', 25, 35, 25, 20, 80),
(19, 'Blazing Champion', 'A warrior who fights with the fury of flames.', 'cards/BlazingChampion.jpg', 'warrior', 'fire', 50, 25, 40, 35, 125),
(20, 'Elder Sage', 'A mage wise beyond years.', 'cards/ElderSage.jpg', 'mage', 'arcane', 20, 40, 30, 15, 85),
(21, 'Shadowblade', 'A rogue whose blade strikes from the shadows.', 'cards/Shadowblade.jpg', 'rogue', 'darkness', 35, 30, 40, 25, 100),
(22, 'Iron Sentinel', 'A knight whose duty is unwavering.', 'cards/IronSentinel.jpg', 'knight', 'earth', 45, 25, 30, 35, 110),
(23, 'Sacred Protector', 'A cleric who guards sacred grounds.', 'cards/SacredProtector.jpg', 'cleric', 'light', 40, 45, 20, 30, 110),
(24, 'Harmonious Bard', 'A bard whose melodies enchant all who hear.', 'cards/HarmoniousBard.jpg', 'bard', 'wind', 30, 35, 25, 20, 90),
(25, 'Inferno Knight', 'A knight who wields the power of fire.', 'cards/InfernoKnight.jpg', 'warrior', 'fire', 45, 30, 35, 25, 95),
(26, 'Mystic Enchanter', 'A mage with a talent for enchantments.', 'cards/mysticEnchanter.jpg', 'mage', 'arcane', 25, 35, 30, 20, 85),
(27, 'Silent Thief', 'A rogue who steals without a trace.', 'cards/silentThief.jpg', 'rogue', 'darkness', 20, 25, 35, 20, 75),
(28, 'Defender of the Realm', 'A knight sworn to protect the kingdom.', 'cards/defenderoftheRealm.jpg', 'knight', 'earth', 40, 30, 30, 35, 95),
(29, 'Blessed Healer', 'A cleric with a holy touch.', 'cards/blessedHealer.jpg', 'cleric', 'light', 30, 35, 25, 20, 80),
(30, 'Storm Bard', 'A bard who controls the power of storms.', 'cards/stormBard.jpg', 'bard', 'wind', 20, 35, 30, 15, 75),
(31, 'Crimson Berserker', 'A warrior driven by rage.', 'cards/crimsonBerserker.jpg', 'warrior', 'fire', 50, 25, 45, 35, 135),
(32, 'Arcane Scholar', 'A mage with deep knowledge of the arcane.', 'cards/arcaneScholar.jpg', 'mage', 'arcane', 20, 35, 30, 20, 85),
(33, 'Nightshade', 'A rogue skilled in the use of poison.', 'cards/nightShade.jpg', 'rogue', 'darkness', 25, 30, 40, 20, 90),
(34, 'Stone Guardian', 'A knight with an unbreakable shield.', 'cards/StoneGuardian.jpg', 'knight', 'earth', 45, 25, 30, 40, 110),
(35, 'Radiant Cleric', 'A cleric who shines with holy light.', 'cards/radiantCleric.jpg', 'cleric', 'light', 35, 45, 20, 25, 95),
(36, 'Whispering Bard', 'A bard who tells secrets through song.', 'cards/bardvalor.jpg', 'bard', 'wind', 20, 25, 25, 20, 65),
(37, 'Ember Knight', 'A knight whose sword blazes with fire.', 'cards/emberKnight.jpg', 'warrior', 'fire', 45, 30, 35, 25, 95),
(38, 'Frost Sorcerer', 'A mage with power over ice.', 'cards/frostSorcerer.jpg', 'mage', 'ice', 20, 35, 30, 25, 85),
(39, 'Veiled Assassin', 'A rogue cloaked in mystery.', 'cards/veiledAssassin.jpg', 'rogue', 'darkness', 30, 25, 35, 20, 75),
(40, 'Solar Paladin', 'A knight empowered by the sun.', 'cards/image40.jpg', 'knight', 'earth', 40, 30, 30, 40, 110),
(41, 'Lunar Guardian', 'A knight who draws strength from the moon.', 'cards/image41.jpg', 'knight', 'earth', 40, 20, 25, 35, 105),
(42, 'Divine Bard', 'A bard blessed by the divine.', 'cards/image42.jpg', 'bard', 'wind', 25, 30, 25, 20, 75),
(43, 'Infernal Warrior', 'A warrior fueled by infernal power.', 'cards/image43.jpg', 'warrior', 'fire', 50, 25, 45, 35, 135),
(44, 'Arcane Scholar', 'A mage with deep knowledge of the arcane.', 'cards/image44.jpg', 'mage', 'arcane', 20, 35, 30, 20, 85),
(45, 'Nightshade', 'A rogue skilled in the use of poison.', 'cards/image45.jpg', 'rogue', 'darkness', 25, 30, 40, 20, 90),
(46, 'Stone Guardian', 'A knight with an unbreakable shield.', 'cards/image46.jpg', 'knight', 'earth', 45, 25, 30, 40, 110),
(47, 'Radiant Cleric', 'A cleric who shines with holy light.', 'cards/image47.jpg', 'cleric', 'light', 35, 45, 20, 25, 95),
(48, 'Whispering Bard', 'A bard who tells secrets through song.', 'cards/image48.jpg', 'bard', 'wind', 20, 25, 25, 20, 65),
(49, 'Ember Knight', 'A knight whose sword blazes with fire.', 'cards/image49.jpg', 'warrior', 'fire', 45, 30, 35, 25, 95),
(50, 'Frost Sorcerer', 'A mage with power over ice.', 'cards/image50.jpg', 'mage', 'ice', 20, 35, 30, 25, 85);


