-- Insertion des données
INSERT INTO starter_card (id, name, description, img_url, family, affinity, hp, energy, attack, defense, prix) VALUES
(1, 'Warrior of Light', 'A brave warrior of the ancient order.', 'static/cards/bardvalor.jpg', 'warrior', 'fire', 20, 15, 25, 20, 55),
(2, 'Mystic Mage', 'A mage with unparalleled control over arcane forces.', 'https://example.com/image2.jpg', 'mage', 'arcane', 15, 30, 20, 10, 55),
(3, 'Shadow Rogue', 'A rogue that moves unseen in the shadows.', 'https://example.com/image3.jpg', 'rogue', 'darkness', 25, 20, 30, 15, 70),
(4, 'Valiant Knight', 'A knight who defends the realm with honor.', 'https://example.com/image4.jpg', 'knight', 'earth', 30, 15, 25, 30, 75),
(5, 'Holy Cleric', 'A cleric with divine healing powers.', 'https://example.com/image5.jpg', 'cleric', 'light', 25, 30, 15, 20, 70),
(6, 'Bard of Valor', 'A bard who inspires courage through song.', 'https://example.com/image6.jpg', 'bard', 'wind', 15, 20, 15, 10, 45),
(7, 'Fiery Warrior', 'A warrior who channels the power of fire.', 'https://example.com/image7.jpg', 'warrior', 'fire', 35, 25, 30, 20, 85),
(8, 'Arcane Wizard', 'A wizard with mastery over arcane arts.', 'https://example.com/image8.jpg', 'mage', 'arcane', 10, 40, 20, 15, 70),
(9, 'Silent Assassin', 'A rogue known for silent takedowns.', 'https://example.com/image9.jpg', 'rogue', 'darkness', 30, 25, 35, 20, 85),
(10, 'Guardian Knight', 'A knight dedicated to protecting the weak.', 'https://example.com/image10.jpg', 'knight', 'earth', 40, 20, 25, 35, 105),
(11, 'Divine Priest', 'A cleric with a connection to the divine.', 'https://example.com/image11.jpg', 'cleric', 'light', 30, 35, 20, 25, 85),
(12, 'Songweaver', 'A bard who weaves magic into their music.', 'https://example.com/image12.jpg', 'bard', 'wind', 20, 30, 25, 20, 75),
(13, 'Dragon Slayer', 'A warrior famed for slaying dragons.', 'https://example.com/image13.jpg', 'warrior', 'fire', 45, 35, 40, 25, 110),
(14, 'Ice Sorcerer', 'A mage with control over ice and snow.', 'https://example.com/image14.jpg', 'mage', 'ice', 15, 35, 30, 20, 75),
(15, 'Night Stalker', 'A rogue who prowls under the cover of night.', 'https://example.com/image15.jpg', 'rogue', 'darkness', 25, 20, 35, 25, 80),
(16, 'Steel Paladin', 'A knight in shining armor.', 'https://example.com/image16.jpg', 'knight', 'earth', 40, 15, 30, 35, 90),
(17, 'Celestial Healer', 'A cleric with unmatched healing abilities.', 'https://example.com/image17.jpg', 'cleric', 'light', 35, 40, 20, 25, 95),
(18, 'Windrunner', 'A bard swift as the wind.', 'https://example.com/image18.jpg', 'bard', 'wind', 25, 35, 25, 20, 80),
(19, 'Blazing Champion', 'A warrior who fights with the fury of flames.', 'https://example.com/image19.jpg', 'warrior', 'fire', 50, 25, 40, 35, 125),
(20, 'Elder Sage', 'A mage wise beyond years.', 'https://example.com/image20.jpg', 'mage', 'arcane', 20, 40, 30, 15, 85),
(21, 'Shadowblade', 'A rogue whose blade strikes from the shadows.', 'https://example.com/image21.jpg', 'rogue', 'darkness', 35, 30, 40, 25, 100),
(22, 'Iron Sentinel', 'A knight whose duty is unwavering.', 'https://example.com/image22.jpg', 'knight', 'earth', 45, 25, 30, 35, 110),
(23, 'Sacred Protector', 'A cleric who guards sacred grounds.', 'https://example.com/image23.jpg', 'cleric', 'light', 40, 45, 20, 30, 110),
(24, 'Harmonious Bard', 'A bard whose melodies enchant all who hear.', 'https://example.com/image24.jpg', 'bard', 'wind', 30, 35, 25, 20, 90),
(25, 'Inferno Knight', 'A knight who wields the power of fire.', 'https://example.com/image25.jpg', 'warrior', 'fire', 45, 30, 35, 25, 95),
(26, 'Mystic Enchanter', 'A mage with a talent for enchantments.', 'https://example.com/image26.jpg', 'mage', 'arcane', 25, 35, 30, 20, 85),
(27, 'Silent Thief', 'A rogue who steals without a trace.', 'https://example.com/image27.jpg', 'rogue', 'darkness', 20, 25, 35, 20, 75),
(28, 'Defender of the Realm', 'A knight sworn to protect the kingdom.', 'https://example.com/image28.jpg', 'knight', 'earth', 40, 30, 30, 35, 95),
(29, 'Blessed Healer', 'A cleric with a holy touch.', 'https://example.com/image29.jpg', 'cleric', 'light', 30, 35, 25, 20, 80),
(30, 'Storm Bard', 'A bard who controls the power of storms.', 'https://example.com/image30.jpg', 'bard', 'wind', 20, 35, 30, 15, 75),
(31, 'Crimson Berserker', 'A warrior driven by rage.', 'static/cards/crimsonBerserker.jpg', 'warrior', 'fire', 50, 25, 45, 35, 135),
(32, 'Arcane Scholar', 'A mage with deep knowledge of the arcane.', 'static/cards/arcaneScholar.jpg', 'mage', 'arcane', 20, 35, 30, 20, 85),
(33, 'Nightshade', 'A rogue skilled in the use of poison.', 'static/cards/nightShade.jpg', 'rogue', 'darkness', 25, 30, 40, 20, 90),
(34, 'Stone Guardian', 'A knight with an unbreakable shield.', 'static/cards/StoneGuardian.jpg', 'knight', 'earth', 45, 25, 30, 40, 110),
(35, 'Radiant Cleric', 'A cleric who shines with holy light.', 'static/cards/radiantCleric.jpg', 'cleric', 'light', 35, 45, 20, 25, 95),
(36, 'Whispering Bard', 'A bard who tells secrets through song.', 'static/cards/bardvalor.jpg', 'bard', 'wind', 20, 25, 25, 20, 65),
(37, 'Ember Knight', 'A knight whose sword blazes with fire.', 'static/cards/emberKnight.jpg', 'warrior', 'fire', 45, 30, 35, 25, 95),
(38, 'Frost Sorcerer', 'A mage with power over ice.', 'static/cards/frostSorcerer.jpg', 'mage', 'ice', 20, 35, 30, 25, 85),
(39, 'Veiled Assassin', 'A rogue cloaked in mystery.', 'static/cards/veiledAssassin.jpg', 'rogue', 'darkness', 30, 25, 35, 20, 75),
(40, 'Solar Paladin', 'A knight empowered by the sun.', '/cards/SolarPaladin.jpg', 'knight', 'earth', 40, 30, 30, 40, 110),
(41, 'Lunar Guardian', 'A knight who draws strength from the moon.', '/cards/LunarGuardian.jpg', 'knight', 'earth', 40, 20, 25, 35, 105),
(42, 'Divine Bard', 'A bard blessed by the divine.', '/cards/DivineBard.jpg', 'bard', 'wind', 25, 30, 25, 20, 75),
(43, 'Infernal Warrior', 'A warrior fueled by infernal power.', '/cards/InfernalWarrior.jpg', 'warrior', 'fire', 50, 25, 45, 35, 135),